---
name: local-llm

services:
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    ports:
      - "0.0.0.0:8411:8411"
    environment:
      - SEARXNG_PORT=8411
    volumes:
      - ./core-config/:/etc/searxng/:z
      - core-data:/var/cache/searxng/

  open-webui:
    container_name: open-webui
    # Note: Web retrieval is broken in v0.9.5
    image: ghcr.io/open-webui/open-webui:v0.9.4
    restart: always
    network_mode: host
    volumes:
      - owui-data:/app/backend/data:Z
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - SEARXNG_API_URL=http://localhost:8411
      - OPENAI_API_BASE_URL=https://router.huggingface.co/v1

volumes:
  core-data:
  owui-data:
